# Default values for helm-package.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/maliaga-pantoja/sesion5"
  tag: "bc87fc77a74963b6c18bce8f7d32bc0d75b76008"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  domain: smda.api.wyracocha.com

autoscaling:
  replicaCount: 3
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80